---
- hosts: linux 
  become: True
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: "latest"
    - name: Install packages
      dnf:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
    - name: Install required packages
      become: true
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Add Docker repository
      become: true
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      become: true
      dnf:
        name: docker-ce
        state: latest

    - name: Start Docker service
      become: true
      systemd:
        name: docker
        enabled: yes
        state: started

...