---
- hosts: linux 
  become: True
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: "latest"
    - name: Install packages
      dnf:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...