---
- hosts: linux 
  become: True
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: "latest"

    - name: Install required packages
      become: true
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest

    - name: Install Docker
      become: true
      dnf:
        name: docker.x86_64
        state: latest

    - name: Start Docker service
      become: true
      systemd:
        name: docker
        enabled: yes
        state: started

...